"""add user ownership

Revision ID: 0cee0df426df
Revises: aa8816253ec7
Create Date: 2026-08-10 07:15:59.512984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cee0df426df'
down_revision: Union[str, Sequence[str], None] = 'aa8816253ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'receipts', 'users', ['user_id'], ['id'])
    op.add_column('recurring_bills', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recurring_bills_user_id'), 'recurring_bills', ['user_id'], unique=False)
    op.create_foreign_key(None, 'recurring_bills', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint(None, 'recurring_bills', type_='foreignkey')
    op.drop_index(op.f('ix_recurring_bills_user_id'), table_name='recurring_bills')
    op.drop_column('recurring_bills', 'user_id')
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_column('receipts', 'user_id')
    # ### end Alembic commands ###
